FROM docker.io/dlang2/ldc-ubuntu:latest

WORKDIR /app
COPY . .

ENV DC=ldc2
RUN dub build --build=release --compiler=ldc2

EXPOSE 8080
ENV PORT=8080
ENV BIND_ADDRESS=0.0.0.0

CMD ["./service-portfolio"]